#!/usr/bin/env sh
. "${0%/*}/h"

echo "running precommit"
current_branch=$(git branch --show-current)
if [ "$current_branch" = "main" ] || [ "$current_branch" = "dev" ]; then
  echo "You can't push to $current_branch branch directly."
  exit 1
fi

npx lint-staged
